version: "3.8"

services:

  postgresql:
    image: postgres:14.5
    container_name: postgresql

    volumes:
      - ./data/db:/postgresql
      - ./sql/V1_create_tables.sql:/docker-entrypoint-initdb.d/V1_create_tables.sql

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test_bk
    ports:
      - "5432:5432"
    networks:
      - microservices-network

  pgadmin:
    image: dpage/pgadmin4:6.11
    container_name: pgadmin4

    volumes:
      - ./data/pgamin-data:/pgadmin

    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root

    ports:
      - "5050:80"
    networks:
      - microservices-network

  schedular_payments:
    container_name: schedular_service
    image: schedular_payments:latest
    build:
      dockerfile: Dockerfile
      context: ./SchedularPayments
    ports:
      - "8083:8083"
    networks:
      - microservices-network

  bank_account:
    container_name: bank_account
    image: bank_account:latest
    build:
      dockerfile: Dockerfile
      context: ./BankAccount
    ports:
      - "8082:8082"
    networks:
      - microservices-network

  payments:
    container_name: payments_service
    image: payments:latest
    build:
      dockerfile: Dockerfile
      context: ./Payments
    ports:
      - "8081:8081"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge